version: '3'
services:
     homepage:
       image: ghcr.io/gethomepage/homepage:latest
       container_name: homepage
       environment:
         - PUID=${PUID:-1000}
         - PGID=${PGID:-1000}
         - HOMEPAGE_ALLOWED_HOSTS=${SERVER_IP:-localhost}:3000
       ports:
         - 3000:3000
       volumes:
         - ./homepage/config:/app/config
         - /var/run/docker.sock:/var/run/docker.sock:ro
       restart: unless-stopped
     jellyfin:
       image: jellyfin/jellyfin:latest
       container_name: jellyfin
       environment:
         - PUID=${PUID:-1000}
         - PGID=${PGID:-1000}
       ports:
         - 8096:8096
       volumes:
         - ./jellyfin/config:/config
         - ${MEDIA_PATH:-/media}/movies:/data/movies
         - ${MEDIA_PATH:-/media}/shows:/data/shows
       restart: unless-stopped
     jellyseerr:
       image: hotio/jellyseerr:latest
       container_name: jellyseerr
       environment:
         - PUID=${PUID:-1000}
         - PGID=${PGID:-1000}
       ports:
         - 5055:5055
       volumes:
         - ./jellyseerr/config:/config
       restart: unless-stopped
     sonarr:
       image: linuxserver/sonarr:latest
       container_name: sonarr
       environment:
         - PUID=${PUID:-1000}
         - PGID=${PGID:-1000}
       ports:
         - 8989:8989
       volumes:
         - ./sonarr/config:/config
         - ${MEDIA_PATH:-/media}/shows:/tv
         - ${TORRENTS_PATH:-/torrents}:/downloads
       restart: unless-stopped
     radarr:
       image: linuxserver/radarr:latest
       container_name: radarr
       environment:
         - PUID=${PUID:-1000}
         - PGID=${PGID:-1000}
       ports:
         - 7878:7878
       volumes:
         - ./radarr/config:/config
         - ${MEDIA_PATH:-/media}/movies:/movies
         - ${TORRENTS_PATH:-/torrents}:/downloads
       restart: unless-stopped
     prowlarr:
       image: linuxserver/prowlarr:latest
       container_name: prowlarr
       environment:
         - PUID=${PUID:-1000}
         - PGID=${PGID:-1000}
       ports:
         - 9696:9696
       volumes:
         - ./prowlarr/config:/config
       restart: unless-stopped
     qbittorrent:
       image: linuxserver/qbittorrent:latest
       container_name: qbittorrent
       environment:
         - PUID=${PUID:-1000}
         - PGID=${PGID:-1000}
       ports:
         - 8080:8080
       volumes:
         - ./qbittorrent/config:/config
         - ${TORRENTS_PATH:-/torrents}:/downloads
       restart: unless-stopped
     flaresolverr:
       image: flaresolverr/flaresolverr:latest
       container_name: flaresolverr
       environment:
         - PUID=${PUID:-1000}
         - PGID=${PGID:-1000}
       ports:
         - 8191:8191
       restart: unless-stopped